//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExamples.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public Nullable<int> depId { get; set; }
        public string designation { get; set; }
        public string gender { get; set; }
        public string hobbies { get; set; }
        public string ephoto { get; set; }
    }
}
